### ISSUE TITLE
Finish designing protocol requirements v1

### ISSUE THREAD

**Issue by criadoperez** [originalworks/protocol#14]
https://miro.com/app/board/uXjVK29EbYU=/

**Comment by revelator-labs** [comment]
@criadoperez I've updated Miro link. should we change anything about the permissions of this new board?

**Comment by criadoperez** [comment]
Looks good. Now that it only contains the OW design, I also made the link open to view by anyone.

I also noticed we had the OW diagrams on two links (the old one and the one above), and we were editing both separately.  To avoid this problem I moved the relevant diagrams to just the link above. 

So now the diagrams are just in one place.
