### ISSUE TITLE
Validate ERN message for ISRC creation

### ISSUE THREAD

**Issue by criadoperez** [originalworks/protocol#20]
We need to validate the [ERN_example](https://github.com/originalworks/protocol/blob/main/DDEX_messages/ERN_example.xml) for registering new ISRCs.

**Comment by criadoperez** [comment]
I'm implementing 4.3 right now. 
Once completed we can see if it  works with 3.8.2 directly or if we would need to make any modifications for it.
Would that work?

**Comment by revelator-labs** [comment]
Pending samples of ERN 4.3 intended to be automatically generated by  Revelaotr. 

ETA to begin integration: October 1
