### ISSUE TITLE
Validate MWN message for ISWC creation

### ISSUE THREAD

**Issue by criadoperez** [originalworks/protocol#21]
Validate the [MWN](https://github.com/originalworks/protocol/blob/main/DDEX_messages/MWN_example.xml) file format to register a new ISWC and link it to an ISRC

**Comment by revelator-labs** [comment]
We agreed that `SharePercentage` 0-100 will be recorded per entry (ISWC/RightType/Territory) and as part of the validation if more than 100% is claimed across parties, a flag is raised and the exception will need to be handled
