### ISSUE TITLE
Provide a method to declare a link between ISRC and ISWC / include conflict resolution

### ISSUE THREAD

**Issue by revelator-labs** [originalworks/protocol#30]
Currently there are 2 known and acceptable methods: 

1. **MWN** - as part of the Musical Work description; each time a new ISRC is linked to an existing ISWC a new message including the new track needs to be sent ! - This means that all the existing ISRCs need to be included in the new message (as all other data), otherwise they will be considered "disconnected" @criadoperez we should indeed confirm this is DDEX standard behavior.. 

2. **ERN** - as part of a Release description; Should we allow overwriting ISWCs in a release? I'm not sure that should be permissible; I think we should require creating a new release notification if to map between an ISRC and ISWC through an ERN - If the previous release needs to be omitted, then the data provider should use the existing [Takedown message](https://github.com/originalworks/protocol/blob/main/DDEX_messages/ERN_TakedownMessage_example.xml) - Alternatively we may ignore ISWC info in ERN and require explicit MWN notifications to declare the connection (considering, many data providers may have noise in their ERN massages)

Appart from the DDEX standard we will also need to support CWR messages. That will be defined as a separate milestone

**Comment by revelator-labs** [comment]
@criadoperez I agree that putting it in an MWN makes more sense, but since all of our messages will be tied to release notifications, we might not be able to rely on MWN being generated. 

I would try to first stick with requiring the inclusion of the ISWC in the ERN and using that as the default. Then we should learn if publishers will indeed be able send MWNs or if we will need to accept(the nonDDEX) CWR message first. 

If agreed. I will define that ERN is the first message supported in V1 and ISWCs must be declared in that message if they want to make a link.

**Comment by revelator-labs** [comment]
*by "requiring" I mean, making it optional to declare the ISWC but not compolsary

**Comment by criadoperez** [comment]
Correct. 
Closing issue as will manage this with CWR
