### ISSUE TITLE
Support CWR file formats for registering ISWCs

### ISSUE THREAD

**Issue by revelator-labs** [originalworks/protocol#31]

**Comment by revelator-labs** [comment]
https://www.notion.so/revelator/GitHub-weso-CWR-DataApi-CWR-DataApi-3c0cb6763edd4171b2efd17ff10ea772?pvs=4

**Comment by revelator-labs** [comment]
@criadoperez; We have [this work](https://chatgpt.com/share/284bf66a-c650-4a96-b55a-7d1df87a01b8) done by Bruno regarding the validation for CWR

**Comment by criadoperez** [comment]
@revelator-labs this would be after the ISWC is registered with an MWN message right?

**Comment by revelator-labs** [comment]
Pending prioritization; 
@criadoperez - Trying to be efficient, I am thinking that currently we can receive ISWC within an ERN message already in scope.  We can include the ISWC field in the in the ERN message that will be created by our software package and insert that as the "current" known ISWC; 

Once we have the first partner who is managing ISWCs (any publisher or royalty society) who will require CWR (or MWN) to report ISWCs we can add those parsers... 

Regardless of the message type, the Data Provider will have to declare if they are registering the ISRC, ISWC (or both) as the record they control in order to add the ISWC or ISCC as a record that can have a license. For example: the distributor may have an ISWC on record because that's what the rights holder reported, but the distributor should not be allowed to create a `deal` for the ISWC; (typically) a different data provider (the publisher) will have to send a message declaring the ISWC they are controlling and if it matches an existing record and they also provide the same ISRC as received in the original ERN from the distributor then great; if it s conflicting, then the asset needs to be flagged as conflicting records, but still this should not prevent each DP from monetizing the asset they control. 
*Only in the case that another data provider is claiming to be the `Rights Controller` of an identifier that already has a registered `Rights Controller` should be blocked from creating licenses...
