### ISSUE TITLE
Publish xsd from the repository

### ISSUE THREAD

**Issue by criadoperez** [originalworks/protocol#36]
We need to create a gihub action that automatically publishes the xsd files to a public site of original works.

One approach can be to use Github pages to publish them on an independent subdomain like: http://xml.original.works

**Comment by criadoperez** [comment]
Update: @michalgrzegor suggested hosting the files on IPFS instead of Github pages. So the url to fetch the file would be: https://ipfs.original.works/

**Comment by michalgrzegor** [comment]
@criadoperez Unfortunately, every time we add a file to a folder its Cid will change. We can, of course, bypass this problem by using e.g. nginx proxy and automatically updating the URL to which we redirect traffic.

**Comment by criadoperez** [comment]
We go back to using Github pages instead?

**Comment by michalgrzegor** [comment]
Can we upload files to github pages? I think github pages is for serving static pages.

**Comment by michalgrzegor** [comment]
@criadoperez Another option is that we add the file to ipfs and then edit the list of pinned files that is in this repository.

**Comment by criadoperez** [comment]
> Can we upload files to github pages? I think github pages is for serving static pages.

It is. That's the advantage. They are just xsd files. Redeployed each time if they are changed.

> @criadoperez Another option is that we add the file to ipfs and then edit the list of pinned files that is in this repository.

Yes we could, but if we do this, the xsd files would have to get uploaded to ipfs every time they are created on edited in this repository. Seems it would be overcomplicating it no?

**Comment by michalgrzegor** [comment]
What should flow look like? xsd files are committed to this repository? Is this one edited file or is this a folder where files are added?

**Comment by criadoperez** [comment]
@michalgrzegor

I created the github action and activated pages.

So now every file that is in the `xsd` folder is published into the site `https://originalworks.github.io/protocol/`

For example: `https://originalworks.github.io/protocol/MWN.xsd`

Please now create a CNAME registry in the original.work domain so `xml.original.works` domain can be used instead of github.io.

**Comment by criadoperez** [comment]
Done.
