### ISSUE TITLE
Define DDEX validations done by the protocol for Original Works Records

### ISSUE THREAD

**Issue by revelator-labs** [originalworks/protocol#37]

**Comment by revelator-labs** [comment]
### Records: 

Unique Record consists of `PUBLIC` entries that include a unique combination of:

1.  `MusicalWork` (usually ISWC) OR `Resource` (Usually ISRRC)
2. `Territory[]`
3. `RightType[]` 
4. `RightSharePercentage`* (0.01-100.00%)

*There could be **multiple unique records** of the same 3 values by different `RightsControllers` as long as they all add up to <=100%; if >100% is registered by verified data providers then the following actions are blocked until records are sorted:  for is blocked  

1. Creation of `deals` for any of the records
2. Paying out royalties from the poll to any of the deals collecting royalties.

**Comment by revelator-labs** [comment]
If a `RightsController` sends the same unique record again the protocol will render the current record `invalid`, and add the message date as the `endDate` of the initial record, and create a new valid record.  

*As we are planning to enable tokenization of governance per "record" this will rquire minting new contracts and migrating tokens for any new Record that has been previously tokenized

**Comment by revelator-labs** [comment]
### Deals:

[Public_field]:Exclusive {YES}
[Private_filed]: start date
[Private_filed]: end date
> New Deal cannot be created if `Exclusive [YES]` && `start date-start date` period overlaps

[Public_field]:Exclusive {NO}
[Public_field]:Licensee []
> New Deal cannot be created if `Exclusive [NO]` && `start date-start date` period overlaps

**Comment by revelator-labs** [comment]
@criadoperez  - 

1. Please note that in the example we need to remove `ReproductionRight` from the "RightsType" and keep only `MakeAvailableRight`

Reproduction refers to the right of creating a physical copy (CD, Vynil, etc..) - in the avs file it is defined as follows: {"const": "ReproductionRight", "description": "The Right to make a physical reproduction of a Work."}

According to the Chat GPT Expert:

""MakeAvailableRight" right is commonly used by distributors, as defined in the DDEX standards, to indicate the permission to offer the content for streaming​​. Therefore, for a distributor managing streaming royalties, "MakeAvailableRight" effectively defines the rights they control in this context."

I have specified that above as validation #4.2

2. I am still not convinced we need to add the territory and share percentage on the affiliate level if we can specify it per track. 

We can declare that they send the percent and territory as the default, and if not specified otherwise on the soundRecording, we take it from the affiliate fields. What do you think?

**Comment by criadoperez** [comment]
> 1. Please note that in the example we need to remove ReproductionRight from the "RightsType" and keep only MakeAvailableRight

Done.

> 2. I am still not convinced we need to add the territory and share percentage on the affiliate level if we can specify it per track. We can declare that they send the percent and territory as the default, and if not specified otherwise on the soundRecording, we take it from the affiliate fields. What do you think?

I agree it's redundant to put in both. However if I remove the territory of the Affiliation it fails the schema validation. So version 4.3 is requiring it. We can remove PercetangeOfRightsAssigments. If we can remove only territory should we still remove it? 
I would recommend using the territory and percentage from affiliation by default, but always replacing it by the one in the sound-recording if it exists.  So sound-recording values have preference.



> 3. I followed the ERN example to specify the ISRC validation - please verify it is specified correctly as well

What do you mean by this?

**Comment by criadoperez** [comment]
@revelator-labs  Regarding the checks:

>    DDEX must include the following fields (beyond the DDEX requirements):
    4.1 Validate the following affiliation is specified PartyList:Party:Affiliation:Type:MusicLicensingCompany
    4.2 Validate the following rights type is specified: PartyList:Party:Affiliation:RightsType:MakeAvailableRight

I assume these two checks should be only for the PartyID that is the MessageSender.

**Comment by revelator-labs** [comment]
@criadoperez - Correct. Since the sender is the party who will eventually have to hold a stake in $OWN they should be the same party that is licensed to distribute and monetize the music.

**Comment by criadoperez** [comment]
### Rewriting the checklist for ERN messages stated above (with the updates of current code): 

The protocol should accept as a `valid` unique Record: an entry that consists of these fields in a unique combination of the following requirements:

CHECK 1 (DONE). Message must comply with DDEX 4.3.
CHECK 2 (DONE). PartyID is whitelisted.

CHECK 4. (DONE)  Validate the following affiliation is specified `PartyList:Party:Affiliation:Type:MusicLicensingCompany`
CHECK 5. (DONE) Validate the following rights type is specified: `PartyList:Party:Affiliation:RightsType:MakeAvailableRight`
CHECK 6 (DONE) . Validate the ISRC is specified for each SoundRecording - `SoundRecording:SoundRecordingEdition:Type:ResourceId:{ISRC}`. Also checks its a 12 digit string

CHECK 7

  4.4 SoundRecording must specify the `Party` which is specified as the `MusicLicensingCompany` (see 4.1 above) as the rights controller 
`ResourceList:SoundRecording:ResourceRightsController:RightsControllerPartyReference`

CHECK 8 (DONE). Validate the type of rights controller for the SoundRecording: `ResourceList:SoundRecording:ResourceRightsController:RightsControlType:RoyaltyAdministrator`

CHECK 9 (PENDING - Define Validate). Validate the share percentage of the rights control for the SoundRecording:  `ResourceList:SoundRecording:ResourceRightsController:RightSharePercentage`

CHECK 10 
  4.7 - Validate SoundRecording specifies at least one of the following usage types - `ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:Stream`
`ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:PermanentDownload`
`ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:ConditionalDownload`
`ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:TetheredDownload`

CHECK 11
  4.8 - Validate the territory is declared: `ResourceList:SoundRecording:ResourceRightsController:TerritoryOfRightsDelegation

CHECK 12
5.`ResourceList:SoundRecording:WorkID:ISWC` (ISWC) of a soundRecord is _optional_ **ONLY** when the ResourceRightsControler of the same SoundRecording is linked to a PartyID with affiliation `Type`:`MusicLicensingCompany` (which currently will be always).

*There could be **multiple unique records** of the same ISRC+territory+RightsType by different `RightsControllers` as long as they all add up to <=100%; if >100% is registered by **verified data providers** then the record status becomes `invalid`, blocking the following anctions from being permitted:

Once all checkes passed:
*  All fields that are not specified in the ERN example will be removed.

**Comment by revelator-labs** [comment]
@criadoperez - If storing additional data will not significantly improve

The reasoning is that we might chose not to parse some metadata on the release or resources but it would be good to have those records available for future indexing... 

The only sensitive information that might be transmitted at this point involves the `Deal` composite, which as far as I understand, can only be included as part of the 'DealList` composite - So I would suggest recommending not to include it in the example, but to specify that all unparsed info will remain in tact except for the  this will be the 'DealList` component that will be explicitly removed. 

When we start ingesting deals (including the private terms) then we can decide if we will allow sending them all in one message - but in any case, we will not want to include that private data on IPFS, so the intial process of removing the deals before pinning to IPFS should be a requirement in any case...

**Comment by criadoperez** [comment]
Will add CHECK 11 so only `Deallist` will be removed.

**Comment by denciu** [comment]
@criadoperez @revelator-labs 

Detailed questions regarding extra validation:

`CHECK 4. Validate the following affiliation is specified PartyList:Party:Affiliation:Type:MusicLicensingCompany`
`PartyList` can have at least one party.
1. 1. Do we accept: at least one/exactly one?

PartyList:Party` can have multiple (or none) affiliations. 
1. Do we accept: none/at least one/exactly one?
1a. If at least one, all of them need to be `Type:MusicLicensingCompany`?

`CHECK 5. Validate the following rights type is specified: PartyList:Party:Affiliation:RightsType:MakeAvailableRight`
`PartyList:Party:Affiliation` can have multiple (or none) `RightsType`s. 
1. Do we accept: none/at least one/exactly one? 
1a. If at least one, all of them need to be `RightsType:MakeAvailableRight`?

`CHECK 6 . Validate the ISRC is specified for each SoundRecording - SoundRecording:SoundRecordingEdition:Type:ResourceId:{ISRC}. Also checks its a 12 digit string`

I think you mean `SoundRecording:SoundRecordingEdition:ResourceId:{ISRC}`.

`ResourceList` can have multiple (or none) `SoundRecording`s.
1. Do we accept: none/at least one/exactly one?

`SoundRecording` can have at least one `SoundRecordingEdition`.
1. Do we accept: at least one/exactly one?

`SoundRecording:SoundRecordingEdition` can have at least one `ResourceId`.
1. Do we accept: at least one/exactly one?
1a. If at least one, we only accept ISRC and ignore other Ids (CatalogNumber, ProprietaryId)?


`CHECK 7. SoundRecording must specify the Party which is specified as the MusicLicensingCompany as the rights controller
ResourceList:SoundRecording:ResourceRightsController:RightsControllerPartyReference`

`SoundRecording` can have multiple (or none) `ResourceRightsController`s.
1. Do we accept: none/at least one/exactly one?

So check would look like "at least one Party in PartyList that has `Type:MusicLicensingCompany`  needs to have PartyReference === ResourceList:SoundRecording:ResourceRightsController:RightsControllerPartyReference ?

`CHECK 8. Validate the type of rights controller for the SoundRecording: ResourceList:SoundRecording:ResourceRightsController:RightsControlType:RoyaltyAdministrator`

`ResourceList:SoundRecording:ResourceRightsController` can have multiple (or none) `RightsControlType`s.
1. Do we accept: none/at least one/exactly one?


`CHECK 9 Ensure the territory is declared: `ResourceList:SoundRecording:ResourceRightsController:TerritoryOfRightsDelegation`

and 

`CHECK 10 Validate SoundRecording specifies at least one of the following usage types - ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:Stream
ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:PermanentDownload
ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:ConditionalDownload
ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:TetheredDownload`

I think you mean `ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:TerritoryOfRightsDelegation`

`ResourceList:SoundRecording:ResourceRightsController` can have multiple (or none) `DelegatedUsageRights`.
1. Do we accept: none/at least one/exactly one?

`ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:TerritoryOfRightsDelegation` can have multiple (or none) `TerritoryOfRightsDelegation` and at least one `UseType`.
1. Do we accept none/at least one/exactly one `TerritoryOfRightsDelegation`?

**Comment by criadoperez** [comment]
> CHECK 4. Validate the following affiliation is specified PartyList:Party:Affiliation:Type:MusicLicensingCompany
PartyList can have at least one party.
>
> Do we accept: at least one/exactly one?


Partylist can have more than one Party. 
All Parties that have Affiliation (will normally be one), have to be of type `MusicLicensingCompany`. 

---

> CHECK 5. Validate the following rights type is specified: PartyList:Party:Affiliation:RightsType:MakeAvailableRight
> PartyList:Party:Affiliation can have multiple (or none) RightsTypes.
>
> Do we accept: none/at least one/exactly one?
> 1a. If at least one, all of them need to be RightsType:MakeAvailableRight?

`MakeAvailableRight` has to be included. They could have more but at least one of them has to be this right.

---

> CHECK 6 . Validate the ISRC is specified for each SoundRecording -  SoundRecording:SoundRecordingEdition:Type:ResourceId:{ISRC}. Also checks its a 12 digit string
>
> I think you mean SoundRecording:SoundRecordingEdition:ResourceId:{ISRC}.

Correct. Right path is `SoundRecording:SoundRecordingEdition:ResourceId:{ISRC}` . Stated wrongly above. 


> ResourceList can have multiple (or none) SoundRecordings.
> 
> Do we accept: none/at least one/exactly one?
> SoundRecording can have at least one SoundRecordingEdition.

If there is a SoundRecording it has to have an ISRC.
However you can also send a resource in resourcelist that is not a soundrecording (like an image) and that's fine. 

> Do we accept: at least one/exactly one?
> SoundRecording:SoundRecordingEdition can have at least one ResourceId.

One. There is only one `ResourceId` for each `SoundRecordingEdition`. 
But `ResourceId` can have more than one field, like `ISRC`, `CatalagoNumber` and `ProprietaryId`

> Do we accept: at least one/exactly one?
> 1a. If at least one, we only accept ISRC and ignore other Ids (CatalogNumber, ProprietaryId)?

ISRC is compulsary. CatalagoNumber and PropiertaryId may exist or not.


---

> CHECK 7. SoundRecording must specify the Party which is specified as the MusicLicensingCompany as the rights controller ResourceList:SoundRecording:ResourceRightsController:RightsControllerPartyReference
> 
> SoundRecording can have multiple (or none) ResourceRightsControllers.
>
> Do we accept: none/at least one/exactly one?
> So check would look like "at least one Party in PartyList that has Type:MusicLicensingCompany needs to have b PartyReference === ResourceList:SoundRecording:ResourceRightsController:RightsControllerPartyReference ?

If `ResourceRightsController` has more than one `RightsControllerPartyReference` , they should all be parties that as specified as  MusicLicensingCompany

---


> CHECK 8. Validate the type of rights controller for the SoundRecording: 
 ResourceList:SoundRecording:ResourceRightsController:RightsControlType:RoyaltyAdministrator
> 
> ResourceList:SoundRecording:ResourceRightsController can have multiple (or none) RightsControlTypes.
> 
> Do we accept: none/at least one/exactly one?

It has to have at least the `RightsControlType` of `RoyaltyAdminnistrator`. More are optional but accepted. 


---

> CHECK 9 Ensure the territory is declared:  ResourceList:SoundRecording:ResourceRightsController:TerritoryOfRightsDelegation`
> 
> and
> 
> CHECK 10 Validate SoundRecording specifies at least one of the following usage types - ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:Stream ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:PermanentDownload ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:ConditionalDownload ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:TetheredDownload
> 
> I think you mean 
ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:TerritoryOfRightsDelegation

That's another way of doing it, but we went with the option of not stating the territory here.
Territory is instead in ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:TerritoryOfRightsDelegation


> ResourceList:SoundRecording:ResourceRightsController can have multiple (or none) DelegatedUsageRights.
> 
> Do we accept: none/at least one/exactly one?

One or more

> ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:TerritoryOfRightsDelegation can have multiple (or none) TerritoryOfRightsDelegation and at least one UseType.
> 
> Do we accept none/at least one/exactly one TerritoryOfRightsDelegation?

Not using this field as stated above

**Comment by criadoperez** [comment]
### Rewriting the checklist for ERN messages stated above (with the updates of current code): 

The protocol should accept as a `valid` unique Record: an entry that consists of these fields in a unique combination of the following requirements:

**CHECK 1**. Message must comply with DDEX 4.3.
**CHECK 2**. PartyID is whitelisted.
**CHECK 3**. Check RightSharePercentage is between 0 an 100. Never negative or above 100. (Schema verifies only its a decimal value).
**CHECK 4**. Validate the following affiliation is specified `PartyList:Party:Affiliation:Type:MusicLicensingCompany`
**CHECK 5**. Validate the following rights type is specified: `PartyList:Party:Affiliation:RightsType:MakeAvailableRight`
**CHECK 6** . Validate the ISRC is specified for each SoundRecording - `SoundRecording:SoundRecordingEdition:ResourceId:{ISRC}`. Also checks its a 12 digit string
**CHECK 7**. SoundRecording must specify the `Party` which is specified as the `MusicLicensingCompany` as the rights controller 
`ResourceList:SoundRecording:ResourceRightsController:RightsControllerPartyReference`
**CHECK 8**. Validate the type of rights controller for the SoundRecording: `ResourceList:SoundRecording:ResourceRightsController:RightsControlType:RoyaltyAdministrator`
**CHECK 9**  Ensure the territory is declared: `ResourceList:SoundRecording:ResourceRightsController:TerritoryOfRightsDelegation
**CHECK 10** Validate SoundRecording specifies at least one of the following usage types - `ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:Stream`
`ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:PermanentDownload`
`ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:ConditionalDownload`
`ResourceList:SoundRecording:ResourceRightsController:DelegatedUsageRights:UseType:TetheredDownload`


Once all checkes passed:
*  All fields that are not specified in the ERN example will be removed.

**Comment by criadoperez** [comment]
We added `deals` today so we need to enforce a new check:

**CHECK 11** .  Verify that `DealList:ReleaseDeal:Deal:DealTerms:TerritoryCode` is same or minor (compatible) to `PartyList:Affiliation:TerritoryCode` of the `ParyID` of the Sender

**Comment by revelator-labs** [comment]
**CHECK 9**  (`ResourceList:SoundRecording:ResourceRightsController:TerritoryOfRightsDelegation`)
may perhaps be omitted **IF** the territory has been reported in the Affiliation composite (`PartyList:Affiliation:TerritoryCode`) - all recordings should inherent the same territory, and may be overwritten by including a different `TerritoryOfRightsDelegation`
