### ISSUE TITLE
Include media (jpg+audio) files with ERN message event.

### ISSUE THREAD

**Issue by revelator-labs** [originalworks/protocol#41]
Add a method to include link to audio files in order to generate ISCC codes.

This will probably be an opt-in process and will require paying an additional fee so we do not want to make this a requirement, but an option..

**Comment by revelator-labs** [comment]
See information about image inclusion here - https://github.com/originalworks/protocol/issues/25#issue-2383815189

**Comment by criadoperez** [comment]
Done in current CLI version.
Files are pinned to IPFS and CID added to ERN messages.
