### ISSUE TITLE
Generate validation node

### ISSUE THREAD

**Issue by criadoperez** [originalworks/protocol#47]
Generate validation node (excluding ZKP and circuits)

**Comment by revelator-labs** [comment]
@cezary-stroczynski - This validation node has to be deployed on Gnosis, correct? 

Does this mean that the $OWN tokens need to be natively minted on Gnosis, or can the validator contract validate the stake amount on Base for example?

**Comment by cezary-stroczynski** [comment]
> @cezary-stroczynski - This validation node has to be deployed on Gnosis, correct?

Yes, validation nodes will interact with contracts deployed on Gnosis.

> Does this mean that the $OWN tokens need to be natively minted on Gnosis, or can the validator contract validate the stake amount on Base for example?

It's technically possible to check $OWN token balance cross-chain but IMO the main $OWN token contract should be on the same chain as validator's contracts for the sake of simplicity. We can have the main $OWN token contract on Gnosis with the minting logic etc. and later on create bridges to allow transfers to other chains. But still the minting and staking will happen on Gnosis.

**Comment by cezary-stroczynski** [comment]
update:

completed:
- create DdexSequencer smart-contract that will receive BLOB transaction and handle DDEX messages queue (enqueue and dequeue)
- deploy DdexSequencer to Holesky and Chiado testnets and send BLOB transaction with KZG commitment and proof
- run local testnet with Consensus Layer (beacon chain), Execution Layer (where smart-contracts live) and Validators
- deploy DdexSequencer to local testnet and send BLOB transaction
- write a .xml file compression method that will comply with the requirements for the BLOB: https://notes.ethereum.org/@vbuterin/proto_danksharding_faq#What-format-is-blob-data-in-and-how-is-it-committed-to <- We are using DEFLATE algorithm for compression and then transform compressed data to be compliant with the requirements
- send compressed and transformed BLOB to testnet
- OWN-VALIDATOR-NODE:
	1) listen to DdexSequencer events on Execution Layer and obtain KZG commitment (unique identifier of the BLOB)
	2) when there is a new message use the KZG commitment to find a blob in the Consensus Layer (beacon chain)
	3) download blob, decompress it and transform it into a text that will be used in ZK circuit
	
	
	
	
TODO:
- pin blob/messages to IPFS
- deploy ZK circuit contracts for proof verification
- in ONW-VALIDATOR-NODE send output of ZK circuit to the DdexSequencer (dequeue)
- emit events with processed data (from ZK circuit output)
- index data in subgraph

**Comment by criadoperez** [comment]
Next week we expect to have working happy-path flow for sending Ddex message, consuming it by validator and the output will be queryable subgraph registry.

zk features and pinning to ipfs will be continued on another issue.
